CREATE DATABASE CELL_COMMERCE;

USE CELL_COMMERCE;

CREATE TABLE PRODUTO(
	ID BIGINT IDENTITY(1,1),
	NOME VARCHAR(50) NOT NULL,
	DESCRICAO VARCHAR(255),
	DISPLAY VARCHAR (30),
	FABRICANTE VARCHAR (80) NOT NULL,
	OS VARCHAR (30),
	PRECO DECIMAL(9,2) NOT NULL,
	PRIMARY KEY(ID)
);

INSERT INTO PRODUTO (NOME, DESCRICAO, DISPLAY, FABRICANTE, OS, PRECO) 
VALUES
('XT8080', 'MEMÓRIA 8GB, ARMAZENAMENTO 256GB, INTERNET 5G', 'AMOLED (6.5)', 'MOTOROLA', 'ANDROID', 700),
('BLASTER-X', 'MEMÓRIA 16GB, ARMAZENAMENTO 512GB, INTERNET 5G', 'AMOLED (6.5) 4K', 'APPLE', 'IOS', 800),
('SX 80', 'MEMÓRIA 8GB, ARMAZENAMENTO 256GB, INTERNET 5G', 'AMOLED (6.5)', 'SAMSUNG', 'ANDROID', 400),
('A 380', 'MEMÓRIA 8GB, ARMAZENAMENTO 256GB, INTERNET 5G', 'AMOLED (6.5)', 'SAMSUNG', 'ANDROID', 300),
('XYK 9090', 'MEMÓRIA 8GB, ARMAZENAMENTO 128GB, INTERNET 4G', 'AMOLED (6.5)', 'MOTOROLA', 'ANDROID', 200),
('IPHONE XWK', 'MEMÓRIA 8GB, ARMAZENAMENTO 256GB, INTERNET 5G', 'AMOLED (6.5)', 'APPLE', 'IOS', 600),
('GALAXY SZY', 'MEMÓRIA 8GB, ARMAZENAMENTO 256GB, INTERNET 5G', 'AMOLED (6.5)', 'SAMSUNG', 'ANDROID', 500),
('V8', 'MEMÓRIA 8GB, ARMAZENAMENTO 256GB, INTERNET 5G', 'AMOLED (6.5)', 'MOTOROLA', 'ANDROID', 777);

SELECT * FROM PRODUTO WHERE PRECO > 500;
SELECT * FROM PRODUTO WHERE PRECO < 500;
SELECT * FROM PRODUTO WHERE PRECO >= 500;

UPDATE PRODUTO SET DESCRICAO = 'MEMÓRIA 24GB, ARMAZENAMENTO 768GB, INTERNET 5G' WHERE ID = 8;

SELECT * FROM PRODUTO WHERE ID = 8;

SELECT * FROM PRODUTO;