USE MASTER
GO

DROP DATABASE IF EXISTS DB_CURSO_DA_MINHA_VIDA
GO

CREATE DATABASE DB_CURSO_DA_MINHA_VIDA
GO

USE DB_CURSO_DA_MINHA_VIDA
GO

CREATE TABLE TB_CATEGORIAS (
    ID BIGINT IDENTITY(1,1),
    CATEGORIA VARCHAR(30) NOT NULL,
    IDADE_MINIMA_RECOMENDADA INT NOT NULL,
    CONSTRAINT PK_TB_CATEGORIAS_ID PRIMARY KEY(ID) 
)
GO

CREATE TABLE TB_CURSOS (
    ID BIGINT IDENTITY (1,1),
    CURSO VARCHAR (50) NOT NULL,
    INSTRUTOR VARCHAR (50),
    DESCRICAO VARCHAR (90),
    DURACAO_HORAS INT,
    PRECO DECIMAL (10,2) NOT NULL,
    CONSTRAINT PK_TB_CURSOS_ID PRIMARY KEY (ID),
    ID_CATEGORIA BIGINT CONSTRAINT FK_TB_CATEGORIAS FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIAS (ID)
)
GO

INSERT INTO TB_CATEGORIAS (CATEGORIA, IDADE_MINIMA_RECOMENDADA) 
VALUES
('TECNOLOGIA', 12),
('GESTÃO DE PESSOAS', 16),
('TECNOLOGIA KIDS', 5),
('DESENVOLVIMENTO PESSOAL KIDS', 6),
('DESENVOLVIMENTO PESSOAL', 14)
GO

INSERT INTO TB_CURSOS (CURSO, INSTRUTOR, DESCRICAO, DURACAO_HORAS, PRECO, ID_CATEGORIA)
VALUES
('LÓGICA DE PROGRAMAÇÃO', 'PLATÃO', 'CONCEITOS BÁSICOS DE LÓGICA DE PROGRAMAÇÃO COM C#', 25, 600.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'TECNOLOGIA')),
('LIDERANÇA DE EQUIPES', 'MARCO AURÉLIO', 'COMO GERENCIAR GRANDES EQUIPES', 35, 1600.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'GESTÃO DE PESSOAS')),
('LÓGICA DE PROGRAMAÇÃO KIDS', 'MARIE CURIE', 'CONCEITOS BÁSICOS DE LÓGICA DE PROGRAMAÇÃO PARA CRIANÇAS COM CODE BLOCKS', 30, 900.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'TECNOLOGIA KIDS')),
('PEQUENOS GRANDES LÍDERES', 'SÉNECA', 'DESENVOLVENDO HABILIDADES ATRAVÉS DE GINCANAS', 45, 3600.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'DESENVOLVIMENTO PESSOAL KIDS')),
('FUTURO BRILHANTE', 'ARISTÓTELES', 'ATINGINDO O AUGE DA COMUNICAÇÃO', 55, 6000.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'DESENVOLVIMENTO PESSOAL')),
('CONCEITOS DE LIDERANÇA', 'ZARINHO XARAIVISKI', 'ADQUIRINDO A POSTURA DE UM LÍDER', 15, 250.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'DESENVOLVIMENTO PESSOAL')),
('FORMAÇÃO DE PESSOAS GESTORAS', 'MARIA DA PENHA', 'TREINAMENTO INTENSIVO NO GERENCIAMENTO DE EQUIPES COM GRANDES PROJETOS', 100, 7900.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'GESTÃO DE PESSOAS')),
('PROGRAMAÇÃO EM BANCO DE DADOS', 'ROBSON ALVES ROCHA', 'PROGRAMAÇÃO EM BANCO DE DADOS SQL SERVER | T-SQL', 50, 1100.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'TECNOLOGIA'))
GO


SELECT P.CURSO, P.INSTRUTOR, CONCAT(P.DURACAO_HORAS, ' HORAS') AS 'CARGA HORÁRIA',  CONCAT('R$ ', P.PRECO) AS VALOR_TOTAL, C.CATEGORIA, CONCAT('+ ',C.IDADE_MINIMA_RECOMENDADA) AS 'IDADE RECOMENDADA'
FROM TB_CURSOS AS P
INNER JOIN TB_CATEGORIAS AS C
ON C.ID = P.ID_CATEGORIA 
WHERE P.PRECO > 500.00

SELECT P.CURSO, P.INSTRUTOR, CONCAT(P.DURACAO_HORAS, ' HORAS') AS 'CARGA HORÁRIA',  CONCAT('R$ ', P.PRECO) AS VALOR_TOTAL, C.CATEGORIA, CONCAT('+ ',C.IDADE_MINIMA_RECOMENDADA) AS 'IDADE RECOMENDADA'
FROM TB_CURSOS AS P
INNER JOIN TB_CATEGORIAS AS C
ON C.ID = P.ID_CATEGORIA 
WHERE P.PRECO BETWEEN 600.00 AND 1000.00

SELECT P.CURSO, P.INSTRUTOR, CONCAT(P.DURACAO_HORAS, ' HORAS') AS 'CARGA HORÁRIA',  CONCAT('R$ ', P.PRECO) AS VALOR_TOTAL, C.CATEGORIA, CONCAT('+ ',C.IDADE_MINIMA_RECOMENDADA) AS 'IDADE RECOMENDADA'
FROM TB_CURSOS AS P
INNER JOIN TB_CATEGORIAS AS C
ON C.ID = P.ID_CATEGORIA 
WHERE P.CURSO LIKE '%J%' OR P.CURSO LIKE '%G%'

SELECT P.CURSO, P.INSTRUTOR, CONCAT(P.DURACAO_HORAS, ' HORAS') AS 'CARGA HORÁRIA',  CONCAT('R$ ', P.PRECO) AS VALOR_TOTAL, C.CATEGORIA, CONCAT('+ ',C.IDADE_MINIMA_RECOMENDADA) AS 'IDADE RECOMENDADA'
FROM TB_CURSOS AS P
INNER JOIN TB_CATEGORIAS AS C
ON C.ID = P.ID_CATEGORIA 

SELECT P.CURSO, P.INSTRUTOR, CONCAT(P.DURACAO_HORAS, ' HORAS') AS 'CARGA HORÁRIA',  CONCAT('R$ ', P.PRECO) AS VALOR_TOTAL, C.CATEGORIA, CONCAT('+ ',C.IDADE_MINIMA_RECOMENDADA) AS 'IDADE RECOMENDADA'
FROM TB_CURSOS AS P
INNER JOIN TB_CATEGORIAS AS C
ON C.ID = P.ID_CATEGORIA 
WHERE C.CATEGORIA = 'GESTÃO DE PESSOAS'