USE MASTER
GO

DROP DATABASE IF EXISTS DB_GENERATION_GAME_ONLINE
GO

CREATE DATABASE DB_GENERATION_GAME_ONLINE;
GO

USE DB_GENERATION_GAME_ONLINE;
GO

CREATE TABLE TB_CLASSES (
    ID BIGINT IDENTITY (1,1),
    NOME_CLASSE VARCHAR (30) NOT NULL,
    TIPO_CLASSE VARCHAR (30) NOT NULL,
    PRIMARY KEY(ID)
)
GO

CREATE TABLE TB_PERSONAGENS (
    ID BIGINT IDENTITY (1,1),
    RACA VARCHAR (30) NOT NULL,
    MONTARIA VARCHAR (40),
    CIDADE_INICIAL VARCHAR (50) NOT NULL,
    TIPO_ARMADURA VARCHAR (50) NOT NULL,
    ATAQUE DECIMAL (10,2),
    DEFESA DECIMAL (10,2),
    CONSTRAINT PK_TB_PERSONAGENS_ID PRIMARY KEY (ID),
    ID_CLASSE BIGINT CONSTRAINT FK_TB_CLASSES_ID FOREIGN KEY (ID_CLASSE) REFERENCES TB_CLASSES (ID)
)
GO


INSERT INTO TB_CLASSES (NOME_CLASSE, TIPO_CLASSE)
VALUES
('MAGO', 'MÁGICA'),
('DRUIDA', 'HÍBRIDO'),
('SHAMAN', 'HÍBRIDO'),
('GUERREIRO', 'CORPORAL'),
('PALADINO', 'HÍBRIDO')
GO

INSERT INTO TB_PERSONAGENS (RACA, MONTARIA, CIDADE_INICIAL, TIPO_ARMADURA, ATAQUE, DEFESA, ID_CLASSE)
VALUES
('ELFO', 'AVESTRUZ', 'GUARULHOS', 'ARMADURA DE PANO', 5000, 500, (SELECT ID FROM TB_CLASSES WHERE NOME_CLASSE = 'MAGO')),
('TAUREN', 'DINOSSAURO', 'SUZANO', 'ARMADURA DE COURO', 3000, 1300, (SELECT ID FROM TB_CLASSES WHERE NOME_CLASSE = 'DRUIDA')),
('ORC', 'LOBO', 'SUZANO', 'ARMADURA DE MALHA DE FERRO', 3000, 1500, (SELECT ID FROM TB_CLASSES WHERE NOME_CLASSE = 'SHAMAN')),
('HUMANO', 'CAVALO', 'RIO DE JANEIRO', 'ARMADURA DE AÇO', 1500, 1500, (SELECT ID FROM TB_CLASSES WHERE NOME_CLASSE = 'GUERREIRO')),
('HUMANO', 'CAVALO', 'FLORIANÓPOLIS', 'ARMADURA DE AÇO', 1800, 2000, (SELECT ID FROM TB_CLASSES WHERE NOME_CLASSE = 'PALADINO')),
('TROLL', 'TIGRE', '', 'ARMADURA DE MALHA DE FERRO', 3000, 1500, (SELECT ID FROM TB_CLASSES WHERE NOME_CLASSE = 'SHAMAN')),
('TAUREN', 'CAPIVARA', 'MOGI DAS CRUZES', 'ARMADURA DE COURO', 3000, 1300, (SELECT ID FROM TB_CLASSES WHERE NOME_CLASSE = 'DRUIDA')),
('ELFO NOTURNO', 'GIRAFA', 'ITAQUERA', 'ARMADURA DE PANO', 5000, 500, (SELECT ID FROM TB_CLASSES WHERE NOME_CLASSE = 'MAGO'))
GO

SELECT P.RACA, P.MONTARIA, P.CIDADE_INICIAL, P.TIPO_ARMADURA, P.ATAQUE, P.DEFESA, C.NOME_CLASSE, C.TIPO_CLASSE FROM TB_PERSONAGENS AS P
INNER JOIN TB_CLASSES AS C
ON 
C.ID = P.ID_CLASSE
WHERE P.ATAQUE > 2000

SELECT P.RACA, P.MONTARIA, P.CIDADE_INICIAL, P.TIPO_ARMADURA, P.ATAQUE, P.DEFESA, C.NOME_CLASSE, C.TIPO_CLASSE FROM TB_PERSONAGENS AS P
INNER JOIN TB_CLASSES AS C
ON 
C.ID = P.ID_CLASSE
WHERE P.DEFESA BETWEEN 1000 AND 2000

SELECT P.RACA, P.MONTARIA, P.CIDADE_INICIAL, P.TIPO_ARMADURA, P.ATAQUE, P.DEFESA, C.NOME_CLASSE, C.TIPO_CLASSE FROM TB_PERSONAGENS AS P
INNER JOIN TB_CLASSES AS C
ON 
C.ID = P.ID_CLASSE
WHERE P.RACA LIKE '%C%'

SELECT P.RACA, P.MONTARIA, P.CIDADE_INICIAL, P.TIPO_ARMADURA, P.ATAQUE, P.DEFESA, C.NOME_CLASSE, C.TIPO_CLASSE FROM TB_PERSONAGENS AS P
INNER JOIN TB_CLASSES AS C
ON 
C.ID = P.ID_CLASSE

SELECT P.RACA, P.MONTARIA, P.CIDADE_INICIAL, P.TIPO_ARMADURA, P.ATAQUE, P.DEFESA, C.NOME_CLASSE, C.TIPO_CLASSE FROM TB_PERSONAGENS AS P
INNER JOIN TB_CLASSES AS C
ON 
C.ID = P.ID_CLASSE
WHERE C.NOME_CLASSE = 'DRUIDA'
