USE MASTER
GO


DROP DATABASE IF EXISTS DB_PIZZARIA_LEGAL
GO

CREATE DATABASE DB_PIZZARIA_LEGAL
GO

USE DB_PIZZARIA_LEGAL
GO

CREATE TABLE TB_CATEGORIAS(
    ID BIGINT IDENTITY(1,1),
    CATEGORIA VARCHAR (30) NOT NULL, --VEGANA, BROTINHO, FRITA, GIGANTE, DOCE
    ESPESSURA_MASSA VARCHAR(30),
    PRIMARY KEY(ID)
)
GO

CREATE TABLE TB_PIZZAS(
    ID BIGINT IDENTITY(1,1),
    NOME VARCHAR (50) NOT NULL,
    INGREDIENTE_PRINCIPAL VARCHAR (30),
    INGREDIENTE_SECUNDÁRIO VARCHAR (30),
    INGREDIENTES_ADICIONAIS VARCHAR (80),
    PRECO DECIMAL (5,2)NOT NULL,
    CONSTRAINT PK_TB_PIZZAS_ID PRIMARY KEY (ID),
    ID_CATEGORIA BIGINT CONSTRAINT FK_TB_CATEGORIAS_ID FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIAS(ID)
)
GO


INSERT INTO TB_CATEGORIAS (CATEGORIA, ESPESSURA_MASSA)
VALUES
('ASSADA', 'FINA'),
('VEGANA', 'FINA'),
('BROTINHO', 'GROSSA'),
('FRITA', 'GROSSA'),
('GIGANTE', 'GROSSA'),
('DOCE', 'FINA')
GO

INSERT INTO TB_PIZZAS (NOME, INGREDIENTE_PRINCIPAL, INGREDIENTE_SECUNDÁRIO, INGREDIENTES_ADICIONAIS, PRECO, ID_CATEGORIA)
VALUES
('MUSSARELA', 'MUSSARELA', 'TOMATE', 'ORÉGANO | MOLHO DE TOMATE',35.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'ASSADA')),
('CALABRESA', 'CALABRESA', 'CEBOLA', 'ORÉGANO | MOLHO DE TOMATE',25.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'BROTINHO')),
('ALHO E ÓLEO', 'ALHO', 'ÓLEO', 'ORÉGANO | AZEITE', 50.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'VEGANA')),
('FRANQUEIJO', 'FRANGO DESFIADO', 'MUSSARELA', 'ORÉGANO | MOLHO DE TOMATE', 150.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'GIGANTE')),
('DOIS QUEIJOS', 'MUSSARELA', 'PROVOLONE', 'ORÉGANO | MOLHO DE TOMATE', 75.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'FRITA')),
('ESCAROLA COM MUSSARELA', 'ESCAROLA', 'QUEIJO VEGANO', 'ORÉGANO | MOLHO DE TOMATE', 60.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'VEGANA')),
('BRIGADEIRO', 'CHOCOLATE BRIGADEIRO', 'GRANULADO DE CHOCOLATE', 'COCO RALADO OPCIONAL', 45.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'DOCE')),
('DOCE DE LEITE', 'DOCE DE LEITE', 'COCO RALADO', 'M&M ADICIONAL', 47.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'DOCE'))
GO

SELECT P.NOME, C.CATEGORIA, C.ESPESSURA_MASSA, P.PRECO FROM TB_PIZZAS AS P
INNER JOIN TB_CATEGORIAS AS C
ON 
C.ID = P.ID_CATEGORIA
WHERE P.PRECO > 45.00

SELECT P.NOME, C.CATEGORIA, C.ESPESSURA_MASSA, P.PRECO FROM TB_PIZZAS AS P
INNER JOIN TB_CATEGORIAS AS C
ON 
C.ID = P.ID_CATEGORIA
WHERE P.PRECO BETWEEN 50.00 AND 100.00

SELECT P.NOME, C.CATEGORIA, C.ESPESSURA_MASSA, P.PRECO FROM TB_PIZZAS AS P
INNER JOIN TB_CATEGORIAS AS C
ON 
C.ID = P.ID_CATEGORIA
WHERE P.NOME LIKE '%M%'

SELECT P.NOME, C.CATEGORIA, C.ESPESSURA_MASSA, P.PRECO FROM TB_PIZZAS AS P
INNER JOIN TB_CATEGORIAS AS C
ON 
C.ID = P.ID_CATEGORIA
ORDER BY P.NOME

SELECT P.NOME, C.CATEGORIA, C.ESPESSURA_MASSA, P.PRECO FROM TB_PIZZAS AS P
INNER JOIN TB_CATEGORIAS AS C
ON 
C.ID = P.ID_CATEGORIA
WHERE C.CATEGORIA = 'VEGANA'
ORDER BY P.NOME


