USE MASTER
GO


DROP DATABASE IF EXISTS DB_FARMACIA_BEM_ESTAR
GO

CREATE DATABASE DB_FARMACIA_BEM_ESTAR
GO

USE DB_FARMACIA_BEM_ESTAR
GO

CREATE TABLE TB_CATEGORIAS(
    ID BIGINT IDENTITY(1,1),
    CATEGORIA VARCHAR(50) NOT NULL,
    SUBCATEGORIA VARCHAR (50) NOT NULL,
    PRIMARY KEY(ID)
)
GO

CREATE TABLE TB_PRODUTOS(
    ID BIGINT IDENTITY(1,1),
    PRODUTO VARCHAR (50) NOT NULL,
    IDADE_MINIMA INT NOT NULL,
    FABRICANTE VARCHAR (50),
    PRECO DECIMAL (10,2) NOT NULL,
    DESCRICAO VARCHAR(100),
    CONSTRAINT PK_TB_PRODUTOS_ID PRIMARY KEY (ID),
    ID_CATEGORIA BIGINT CONSTRAINT FK_TB_CATEGORIAS_ID FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIAS (ID)
)
GO

INSERT INTO TB_CATEGORIAS(CATEGORIA, SUBCATEGORIA)
VALUES
('ESTÉTICA', 'MAQUIAGEM'),
('ESTÉTICA', 'CABELO E PELE'),
('GENÉRICO', 'COM RECEITA'),
('HIGIENE PESSOAL', 'SABONETE'),
('PERFUMARIA', 'DESODORANTE')
GO

INSERT INTO TB_PRODUTOS (PRODUTO, IDADE_MINIMA, FABRICANTE, PRECO, DESCRICAO, ID_CATEGORIA)
VALUES
('BATOM','0', 'MM COSMETIC',10.00,'ESSÊNCIA DE TUTTI-FRUTTI',(SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'ESTÉTICA' AND SUBCATEGORIA = 'MAQUIAGEM')),
('SHAMPOO','0', 'SMX COSMETIC',30.00,'CABELOS DE TODOS OS TIPOS',(SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'ESTÉTICA' AND SUBCATEGORIA = 'CABELO E PELE')),
('VITAMINA CXGH','6', 'LAB BOM',90.00,'COMPLEXO',(SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'GENÉRICO')),
('ROXANA','12', 'NULIEVER',20.00,'PROTEÇÃO 12H',(SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'PERFUMARIA')),
('ESPUMINHA GG','0', 'MM COSMETIC', 3.00,'TODAS AS PELES',(SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'HIGIENE PESSOAL')),
('GEL FIXADOR','6', 'MM COSMETIC',15.00,'NÍVEL 5 DE FIXAÇÃO',(SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'ESTÉTICA' AND SUBCATEGORIA = 'CABELO E PELE')),
('ANALGÉSICO FDS','14', 'LAB NEUO',40.00,'CONTRA DORES',(SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'GENÉRICO')),
('BASE','0', 'FMSS COSMETIC',8.00,'EM PÓ',(SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'ESTÉTICA' AND SUBCATEGORIA = 'MAQUIAGEM'))
GO 

SELECT P.PRODUTO, P.FABRICANTE, C.CATEGORIA, P.PRECO FROM TB_PRODUTOS AS P
INNER JOIN TB_CATEGORIAS AS C
ON 
C.ID = P.ID_CATEGORIA 
WHERE P.PRECO > 50.00

SELECT P.PRODUTO, P.FABRICANTE, C.CATEGORIA, P.PRECO FROM TB_PRODUTOS AS P
INNER JOIN TB_CATEGORIAS AS C
ON 
C.ID = P.ID_CATEGORIA 
WHERE P.PRECO BETWEEN 5.00 AND 60.00

SELECT P.PRODUTO, P.FABRICANTE, C.CATEGORIA, P.PRECO FROM TB_PRODUTOS AS P
INNER JOIN TB_CATEGORIAS AS C
ON 
C.ID = P.ID_CATEGORIA 
WHERE P.PRODUTO LIKE '%C%'

SELECT P.PRODUTO, P.FABRICANTE, C.CATEGORIA, P.PRECO FROM TB_PRODUTOS AS P
INNER JOIN TB_CATEGORIAS AS C
ON 
C.ID = P.ID_CATEGORIA 

SELECT P.PRODUTO, P.FABRICANTE, C.CATEGORIA, P.PRECO FROM TB_PRODUTOS AS P
INNER JOIN TB_CATEGORIAS AS C
ON 
C.ID = P.ID_CATEGORIA 
WHERE C.CATEGORIA = 'ESTÉTICA' AND C.SUBCATEGORIA = 'CABELO E PELE'