USE MASTER
GO

DROP DATABASE IF EXISTS DB_CIDADE_DOS_VEGETAIS
GO

CREATE DATABASE DB_CIDADE_DOS_VEGETAIS
GO

USE DB_CIDADE_DOS_VEGETAIS
GO

CREATE TABLE TB_CATEGORIAS (
    ID BIGINT IDENTITY(1,1),
    CATEGORIA VARCHAR(30) NOT NULL,
    UNIDADE_MEDIDA VARCHAR(15) NOT NULL,
    CONSTRAINT PK_TB_CATEGORIAS_ID PRIMARY KEY(ID) 
)
GO

CREATE TABLE TB_PRODUTOS (
    ID BIGINT IDENTITY (1,1),
    PRODUTO VARCHAR (50) NOT NULL,
    REGIAO_ORIGEM VARCHAR (40),
    RECOMENDACAO VARCHAR (90),
    QUANTIDADE INT,
    PRECO DECIMAL (5,2) NOT NULL,
    CONSTRAINT PK_TB_PRODUTOS_ID PRIMARY KEY (ID),
    ID_CATEGORIA BIGINT CONSTRAINT FK_TB_CATEGORIAS FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIAS (ID)
)
GO

INSERT INTO TB_CATEGORIAS (CATEGORIA, UNIDADE_MEDIDA) 
VALUES
('FRUTAS','KILO'),
('FRUTAS','UNIDADE'),
('LEGUMES','KILO'),
('VERDURAS','UNIDADE'),
('GRÃOS', 'KILO')
GO

INSERT INTO TB_PRODUTOS (PRODUTO, REGIAO_ORIGEM, RECOMENDACAO, QUANTIDADE, PRECO, ID_CATEGORIA)
VALUES
('MAÇÃ', 'PRINCIPALMENTE SUL', 'DEGUSTAÇÃO | VITAMINA', 10,  40.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'FRUTAS' AND UNIDADE_MEDIDA = 'KILO')),
('LARANJA', 'PRINCIPALMENTE SUDESTE', 'DEGUSTAÇÃO | SUCO', 20,  60.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'FRUTAS' AND UNIDADE_MEDIDA = 'KILO')),
('BATATA', 'PRINCIPALMENTE SUL | SUDESTE | NORDESTE', 'DEGUSTAÇÃO | DIETA', 15, 60.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'LEGUMES')),
('MANGA', 'PRINCIPALMENTE NORDESTE', 'DEGUSTAÇÃO | SUCO | SOBREMESA', 20, 100.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'FRUTAS' AND UNIDADE_MEDIDA = 'UNIDADE')),
('ALFACE', 'PRINCIPALMENTE SUDESTE', 'DEGUSTAÇÃO | DIETA', 50, 50.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'VERDURAS')),
('FEIJÃO', 'PRINCIPALMENTE SUL', 'DEGUSTAÇÃO | DIETA', 60, 300.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'GRÃOS')),
('COENTRO', 'PRINCIPALMENTE NORDESTE', 'DEGUSTAÇÃO | TEMPERO', 120, 96.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'VERDURAS')),
('CENOURA', 'PRINCIPALMENTE SUDESTE', 'DEGUSTAÇÃO | DIETA | SUCO', 15, 30.00, (SELECT ID FROM TB_CATEGORIAS WHERE CATEGORIA = 'LEGUMES' AND UNIDADE_MEDIDA = 'KILO'))
GO

SELECT P.PRODUTO, P.RECOMENDACAO, P.QUANTIDADE, CONCAT('R$ ', P.PRECO) AS VALOR_TOTAL, CONCAT('R$ ',CONVERT(DECIMAL(5,2),(P.PRECO/P.QUANTIDADE)), ' POR ', (C.UNIDADE_MEDIDA)) AS 'VALOR UNITÁRIO'
FROM TB_PRODUTOS AS P
INNER JOIN TB_CATEGORIAS AS C
ON C.ID = P.ID_CATEGORIA 
WHERE P.PRECO > 50.00 

SELECT P.PRODUTO, P.RECOMENDACAO, P.QUANTIDADE, CONCAT('R$ ', P.PRECO) AS VALOR_TOTAL, CONCAT('R$ ',CONVERT(DECIMAL(5,2),(P.PRECO/P.QUANTIDADE)), ' POR ', (C.UNIDADE_MEDIDA)) AS 'VALOR UNITÁRIO'
FROM TB_PRODUTOS AS P
INNER JOIN TB_CATEGORIAS AS C
ON C.ID = P.ID_CATEGORIA 
WHERE P.PRECO BETWEEN 50.00 AND 150.00 

SELECT P.PRODUTO, P.RECOMENDACAO, P.QUANTIDADE, CONCAT('R$ ', P.PRECO) AS VALOR_TOTAL, CONCAT('R$ ',CONVERT(DECIMAL(5,2),(P.PRECO/P.QUANTIDADE)), ' POR ', (C.UNIDADE_MEDIDA)) AS 'VALOR UNITÁRIO'
FROM TB_PRODUTOS AS P
INNER JOIN TB_CATEGORIAS AS C
ON C.ID = P.ID_CATEGORIA 
WHERE P.PRODUTO LIKE '%C%'

SELECT P.PRODUTO, P.RECOMENDACAO, P.QUANTIDADE, CONCAT('R$ ', P.PRECO) AS VALOR_TOTAL, CONCAT('R$ ',CONVERT(DECIMAL(5,2),(P.PRECO/P.QUANTIDADE)), ' POR ', (C.UNIDADE_MEDIDA)) AS 'VALOR UNITÁRIO'
FROM TB_PRODUTOS AS P
INNER JOIN TB_CATEGORIAS AS C
ON C.ID = P.ID_CATEGORIA 

SELECT P.PRODUTO, P.RECOMENDACAO, P.QUANTIDADE, CONCAT('R$ ', P.PRECO) AS VALOR_TOTAL, CONCAT('R$ ',CONVERT(DECIMAL(5,2),(P.PRECO/P.QUANTIDADE)), ' POR ', (C.UNIDADE_MEDIDA)) AS 'VALOR UNITÁRIO'
FROM TB_PRODUTOS AS P
INNER JOIN TB_CATEGORIAS AS C
ON C.ID = P.ID_CATEGORIA 
WHERE C.CATEGORIA = 'FRUTAS'